# Generated by Django 5.0 on 2024-01-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workout_auths", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutusermodel",
            name="phone_number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
