# Generated by Django 5.0 on 2024-01-02 04:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workout_auths", "0002_workoutusermodel_phone_number"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="workoutusermodel",
            table="workout_users",
        ),
    ]
