# Generated by Django 5.0 on 2024-01-02 09:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workout_auths", "0004_alter_workoutusermodel_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workoutusermodel",
            name="is_deleted",
        ),
    ]
